### PR TITLE
`cargo update` & lint/clippy/rustfmt/cargo-deny fixes.

### PR DESCRIPTION
**Pull request by eddyb**
This fixes the remaining CI failures.

The `rustfmt.toml` change was prompted by @Firestar99's formatting changes in #2, and the subsequent local rebasing, with `version = "Two"` causing warnings due to:
- https://github.com/rust-lang/rustfmt/pull/6247

So the perma-unstable `rustfmt.toml` `version` config is now `style_edition = "2024"`, and hopefully that gets stabilized at the same time as Rust 2024 becoming stable.

### CODE REVIEW

**Comment by eddyb** [comment]
Oops, just noticed "Ensure compatibility with rust-gpu nightly rust version" check doesn't actually do anything because of how the `rustup` override stuff works, will try to fix that before it gets lost to time again.

**Comment by eddyb** [comment]
"Ensure compatibility with rust-gpu nightly rust version" check works now, it even fully builds with only this warning:
```
warning: unused manifest key: lints.rust.unexpected_cfgs.check-cfg
```
(if we were running `cargo clippy` there might've been issues but it's just `cargo check`)

**Review by LegNeato — APPROVED** [review]
🚀

**Comment by eddyb** [comment]
The merge queue failure was real, literally today's nightly introduced it:
image

Will open another PR.

**Pull request merged**
